name:                coffee-shop-backend
version:             0.1.0.0
github:              "anatolik2509/coffee-shop-backend"
license:             BSD-3-Clause
author:              "Anatoly Antonov"
maintainer:          "antonov250901@gmail.com"
copyright:           "2023 Anatoly Antonov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anatolik2509/coffee-shop-backend#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- http-types
- Decimal
- configurator
- transformers
- resource-pool
- postgresql-simple
- postgresql-migration
- directory
- time
- wai
- wai-extra
- bytestring
- listsafe
- bcrypt
- aeson
- exceptions
- uuid

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  coffee-shop-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coffee-shop-backend

tests:
  coffee-shop-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coffee-shop-backend
